stages:
  - build

build:
  stage: build
  script:
  - nix-build --fallback
  - rm result*
  artifacts:
    untracked: true

shell-864-ghc:
  stage: build
  script:
  - nix-shell --command "echo works" --fallback
  artifacts:
    untracked: true
